
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en.BBJ-kEFzRUI.2018.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAQAiAABQQACAAAAAAAAAACCAAAACAAAAAAAAAAAAAAAAAAAAAAAAAgQAIACABAAAAAAAAAAAAAAIAAAAAAAAGCAAAAhAQAEAAAoAAAAAAAAAAAAAAEAAEAAAAABAAgkA4L_9wQEAAAAAAAAAQAAAAAAAAIAAQAIAAAAAAAAAALgAACAoBgAABCSAAAAAAAAAAAAAAAAAIAAAAAAAAEAAAAAEAIAAAAAACgAAAAAAAAAAAAAAAAACAAAAAAAAAAAAQAAAADgAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEMAAAAAAAAAAAAABAAD8AAAgAAADgAACAEAAAAOCIogEAAAAAAABADgCPB2BIQQEAAAAAAAAAAAAAAAAAAIAAFARzIP2AAAEAAAAAAAAAAAAAAAAAAAAAgBShJtYaABA/dg=0/br=1/rs=ACT90oFwsTulMZ4VWB5_cG4X_F4Dn4NlMg",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.googleapis.com/language/translate/v2"
];
  
