
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.109Mx36OBuM.2018.O/ck=xjs.s._akM-X5GaGg.L.B1.O/am=ACEAAIBACAAAAIABAAAAEAIAUgAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAEQAAAAAAAIEAACAAgAAAAAAAAAAAARAAIIIAEBUEEAlZQsAAAAAgl4QAJACAAAAAAD4AAxyFQAAAAAIAACECBBAAAAJAAAAAAgAAAQQgCAAQAAgAIDATQEBQABCBQAAKBQAIEAAAAIIEAAEJAHIEAAAiYAEkgDgv_3TAQMAAAABAACAAAQADHA2AAELCRAYOAAAAACNuEAAICgMAAAISAAJAAAAACgggAAAAABAAABQAAAAgAAAAA6oC0EIgIAKAEsHDhAAAAQAAABAQIgAAAgIAAAAAIAAECgBQB4AAAAoAQABCAgAvAECDwAAQBABIAIAIAICGACgAIAAAAAAAAKQwE8BIAQIAAA4BQBgBACQADiiaAAAAAAAAACQA8DjARhSUAAAAAAAAAAAAAAAAAAAAIAAFARzIP2CAAEAAAAAAAAAAAAAAAAAAAAAAClCTaw1ACA/d=0/dg=0/br=1/ujg=1/rs=ACT90oFhjKTslZGkNRYErgbayNC5xdbw6A/m=syio,aLUfP,wQlYve,sy9f6,sy2nf,sy33b,sy9f5,sy9f4,sy7mv,sy1zb,sy1zc,sy1yf,sy1y6,sy1xx,sy1yg,sy1ac,pKhWu,sy1xz,n7qy6d,sy1y1,HPGtmd,sy1y4,sy1y5,sy1y2,sypc,sym0,sylx,sylw,syle,syld,sy1x8,uLYJpc,sy95a,pHXghd?xjs=s3",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.google.com/async/bgasy?ei=NY-7aJaIEsadhbIP9qOP4QE&opi=89978449&yv=3&cs=0&async=_fmt:jspb",
  "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.109Mx36OBuM.2018.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAABAAIAIAABUEAAgAAAAAAAAAAQQABAAAAAAAAAAAAAAAAAAAAAAAAAECABAAAAJAAAAAAAAAAAAACAAAAAAAADAAAEAQAACBQAAKAQAAAAAAAAAAAAAAAFAAAAAAIAEEgDgv_3RAQAAAAAAAACAAAAAAAAAAAEACQAAGAAAAAAAuAAAICgMAAAISAABAAAAAAAAAAAAAABAAAAAAAAAgAAAAAgIAAEAAAAKAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAEAAAAA4AAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACGAAAAAAAAAAAAAAQwA8AAAQIAAA4AAAgBAAAADiiaAAAAAAAAACQA8DjARhSUAAAAAAAAAAAAAAAAAAAAIAAFARzIP2AAAEAAAAAAAAAAAAAAAAAAAAAAClCTaw1ACA/d=0/dg=0/br=1/rs=ACT90oFWmBI4NK9QGuOnXq1-n3IRHVLUoQ/m=sb_wiz,aa,abd,sy1yn,sy161,sy15w,sy15l,sy15r,sy16i,async,sy1mn,bgd,sy9av,foot,sy3hu,kyn,sy1qn,sy1qo,lli,sy1of,sy1og,sy6ei,sonic,sy6po,syhy,sy546,sy1o9,sy1o8,sy1lt,sy1c3,sy1c2,sy1c1,sy1c0,sy1c4,sy515,sy516,sy1ca,sy1by,spch,tl,NdLnDf,QKZgZd,zD2Asd,sy1xq,sy1xr,Qj0suc,JXS8fb,sy1ym,sy1fn,sy1yl,sy1yh,sy1y9,sy1yj,sy1yc,sy1ya,sy1ye,sy13t,sy1yb,sy1xw,Wct42,sy1z9,syqc,syoy,sy1x0,sy1wz,syoo,sy1wy,syoq,syma,sym9,syll,sykr,sy1wx,sy1wv,sy1wu,sy1wt,sy1wr,sy1wq,sy1wp,sy1wo,sy1wn,sy1wm,LiBxPe?xjs=s4"
];
  
  